const qs=s=>document.querySelector(s);const qsa=s=>Array.from(document.querySelectorAll(s));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const lerp=(a,b,t)=>a+(b-a)*t;
const norm=(x,a,b)=>clamp((x-a)/(b-a),0,1);
const denorm=(t,a,b)=>a+t*(b-a);
const TEMPO_MIN=60;const TEMPO_MAX=180;
const pitchNames=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}}
const RNG=mulberry32(12345);
const GENRES=["pop","rock","hip-hop","r&b","electronic","house","techno","indie","jazz","classical","latin","afrobeat","k-pop","metal","folk"];
const GENRE_PROFILES={
  "pop":{bpm:[95,130],energy:[0.5,0.8],valence:[0.4,0.8],dance:[0.5,0.85]},
  "rock":{bpm:[90,140],energy:[0.6,0.9],valence:[0.3,0.7],dance:[0.4,0.7]},
  "hip-hop":{bpm:[80,110],energy:[0.5,0.8],valence:[0.3,0.6],dance:[0.6,0.9]},
  "r&b":{bpm:[70,105],energy:[0.4,0.7],valence:[0.3,0.6],dance:[0.5,0.8]},
  "electronic":{bpm:[110,150],energy:[0.6,0.95],valence:[0.3,0.8],dance:[0.6,0.95]},
  "house":{bpm:[118,130],energy:[0.6,0.9],valence:[0.4,0.8],dance:[0.7,0.98]},
  "techno":{bpm:[120,140],energy:[0.7,1.0],valence:[0.1,0.5],dance:[0.6,0.95]},
  "indie":{bpm:[85,130],energy:[0.4,0.8],valence:[0.3,0.8],dance:[0.4,0.8]},
  "jazz":{bpm:[70,140],energy:[0.3,0.6],valence:[0.4,0.8],dance:[0.3,0.6]},
  "classical":{bpm:[60,150],energy:[0.1,0.5],valence:[0.3,0.7],dance:[0.1,0.3]},
  "latin":{bpm:[90,130],energy:[0.5,0.85],valence:[0.5,0.9],dance:[0.6,0.95]},
  "afrobeat":{bpm:[95,120],energy:[0.6,0.9],valence:[0.5,0.9],dance:[0.7,0.98]},
  "k-pop":{bpm:[95,135],energy:[0.6,0.9],valence:[0.4,0.8],dance:[0.6,0.9]},
  "metal":{bpm:[110,180],energy:[0.8,1.0],valence:[0.1,0.5],dance:[0.2,0.5]},
  "folk":{bpm:[70,110],energy:[0.2,0.6],valence:[0.4,0.8],dance:[0.3,0.6]}
};
function randRange(r){return lerp(r[0],r[1],RNG())}
function pick(arr){return arr[Math.floor(RNG()*arr.length)]}
function genTracks(n){const tracks=[];for(let i=0;i<n;i++){const g1=pick(GENRES);const g2=pick(GENRES.filter(g=>g!==g1));const p1=GENRE_PROFILES[g1];const p2=GENRE_PROFILES[g2];const mix=t=>lerp(t[0],t[1],RNG());const bpm=Math.round(lerp(randRange(p1.bpm),randRange(p2.bpm),0.5));const energy=clamp(lerp(randRange(p1.energy),randRange(p2.energy),0.5),0,1);const valence=clamp(lerp(randRange(p1.valence),randRange(p2.valence),0.5),0,1);const dance=clamp(lerp(randRange(p1.dance),randRange(p2.dance),0.5),0,1);const acoustic=clamp(1-energy*0.7+RNG()*0.2,0,1);const instr=clamp((g1==="classical"||g1==="techno"||g1==="house"||g1==="electronic")?0.4+RNG()*0.5:RNG()*0.4,0,1);const key=Math.floor(RNG()*12);const mode=RNG()<0.6?1:0;tracks.push({id:`t${i}`,name:`Track ${String.fromCharCode(65+(i%26))}${Math.floor(i/26)+1}`,artists:[`Artist ${1+(i%17)}`],genres:[g1,g2],features:{energy,valence,danceability:dance,acousticness:acoustic,instrumentalness:instr,tempo:bpm,key,mode}})}return tracks}
let DATA=[];
let LAST_SEQ=[];
function initGenres(){const host=qs("#genres");host.innerHTML="";const set=new Set();DATA.forEach(t=>t.genres.forEach(g=>set.add(g)));const list=Array.from(set).sort();list.forEach(g=>{const lab=document.createElement("label");lab.className="chip";const cb=document.createElement("input");cb.type="checkbox";cb.value=g;lab.appendChild(cb);const span=document.createElement("span");span.textContent=g;lab.appendChild(span);host.appendChild(lab)})}
function getSelectedGenres(){return qsa("#genres input:checked").map(i=>i.value)}
function val(id){return parseFloat(qs(`#${id}`).value)}
function updateDisplays(){qs("#energyVal").textContent=val("energy").toFixed(2);qs("#tempoVal").textContent=String(Math.round(val("tempo")));const tb=qs("#tempoBias");if(tb){qs("#tempoBiasVal").textContent=val("tempoBias").toFixed(2)}qs("#valenceVal").textContent=val("valence").toFixed(2);qs("#danceabilityVal").textContent=val("danceability").toFixed(2);qs("#acousticnessVal").textContent=val("acousticness").toFixed(2);qs("#instrumentalnessVal").textContent=val("instrumentalness").toFixed(2);if(qs("#genreWeight"))qs("#genreWeightVal").textContent=val("genreWeight").toFixed(2);qs("#lengthVal").textContent=String(Math.round(val("length")))}
function tempoScale(){return qs("#tempoBias")?val("tempoBias"):1}
function targetVector(){const e=val("energy"),v=val("valence"),d=val("danceability"),a=val("acousticness"),i=val("instrumentalness"),t=norm(val("tempo"),TEMPO_MIN,TEMPO_MAX)*tempoScale();return [e,v,d,a,i,t]}
function trackVector(tr){const f=tr.features;return [f.energy,f.valence,f.danceability,f.acousticness,f.instrumentalness,norm(f.tempo,TEMPO_MIN,TEMPO_MAX)*tempoScale()]}
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function mag(a){return Math.sqrt(dot(a,a))}
function cosine(a,b){const m=mag(a)*mag(b);return m===0?0:dot(a,b)/m}
function jaccard(a,b){const A=new Set(a),B=new Set(b);let inter=0;A.forEach(x=>{if(B.has(x))inter++});return (inter)/(A.size+B.size-inter||1)}
function energyArc(n,start){const arr=[];for(let i=0;i<n;i++){const t=i/(n-1||1);let e;if(t<0.5){e=lerp(start,0.85,t/0.5)}else if(t<0.8){e=lerp(0.85,0.6,(t-0.5)/0.3)}else{e=lerp(0.6,0.95,(t-0.8)/0.2)}arr.push(clamp(e,0,1))}return arr}
function keyCost(a,b){if(a.key===b.key&&a.mode===b.mode)return 0;if(a.key===b.key&&a.mode!==b.mode)return 0.25;const diff=(b.key-a.key+12)%12;if(diff===7||diff===5)return 0.25;if(diff===2||diff===10)return 0.4;return 1}
function transCost(prev,next){const de=Math.abs(prev.energy-next.energy);const dt=Math.abs(prev.tempo-next.tempo)/60;const k=keyCost(prev,next);return clamp(0.5*de+0.3*dt+0.2*k,0,1)}
function buildPlaylist(){const tg=targetVector();const selG=getSelectedGenres();const gw=qs("#genreWeight")?val("genreWeight"):0.3;const mw=1-gw;const base=DATA.map(tr=>{const vec=trackVector(tr);const mood=cosine(vec,tg);const g=selG.length?jaccard(tr.genres,selG):0.5;const score=mw*mood+gw*g;return {tr,score}}).sort((a,b)=>b.score-a.score);const length=Math.round(val("length"));const pool=base.slice(0,Math.min(base.length,Math.max(length*2,30))).map(x=>x.tr);const arc=energyArc(length,val("energy"));let seq=[];let remaining=new Set(pool.map(t=>t.id));let startCand=[...pool].sort((a,b)=>Math.abs(a.features.energy-arc[0])-Math.abs(b.features.energy-arc[0]))[0]||pool[0];seq.push(startCand);remaining.delete(startCand.id);for(let i=1;i<length;i++){let best=null;let bestScore=-1e9;const prev=seq[seq.length-1];pool.forEach(t=>{if(!remaining.has(t.id))return;const vecScore=cosine(trackVector(t),tg);const gScore=selG.length?jaccard(t.genres,selG):0.5;const baseScore=mw*vecScore+gw*gScore;const tc=transCost(prev.features,t.features);const arcPenalty=Math.abs(t.features.energy-arc[i]);const s=baseScore-0.6*tc-0.4*arcPenalty;if(s>bestScore){bestScore=s;best=t}});if(!best){break}seq.push(best);remaining.delete(best.id)}LAST_SEQ=seq;render(seq,arc);return seq}
function render(seq,arc){const list=qs("#playlist");list.innerHTML="";seq.forEach((t,idx)=>{const li=document.createElement("li");const left=document.createElement("div");left.textContent=`${t.artists[0]} – ${t.name}`;const right=document.createElement("div");right.className="meta";right.textContent=`${t.genres.join(", ")} | E ${t.features.energy.toFixed(2)} | ${t.features.tempo} BPM | ${pitchNames[t.features.key]} ${t.features.mode? "maj":"min"}`;li.appendChild(left);li.appendChild(right);list.appendChild(li)});const avgTempo=Math.round(seq.reduce((s,t)=>s+t.features.tempo,0)/(seq.length||1));const avgEnergy=(seq.reduce((s,t)=>s+t.features.energy,0)/(seq.length||1)).toFixed(2);qs("#summary").textContent=`${seq.length} tracks • Avg tempo ${avgTempo} BPM • Avg energy ${avgEnergy}`;drawViz(seq,arc)}
function drawViz(seq,arc){const c=qs("#viz");const ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);const W=c.width,H=c.height;const pad=40;const plotW=W-pad*2,plotH=H-pad*2;ctx.strokeStyle="#1b2430";ctx.lineWidth=1;for(let i=0;i<=10;i++){const y=pad+i*(plotH/10);ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-pad,y);ctx.stroke()}ctx.strokeStyle="#1b2430";ctx.beginPath();ctx.moveTo(pad,H-pad);ctx.lineTo(W-pad,H-pad);ctx.stroke();if(seq.length===0)return;function x(i){return pad+i*(plotW/Math.max(seq.length-1,1))}function yEnergy(e){return pad+(1-e)*plotH}function yTempo(bpm){return pad+(1-norm(bpm,TEMPO_MIN,TEMPO_MAX))*plotH}ctx.strokeStyle="#2f855a";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x(0),yEnergy(seq[0].features.energy));for(let i=1;i<seq.length;i++){ctx.lineTo(x(i),yEnergy(seq[i].features.energy))}ctx.stroke();ctx.strokeStyle="#3182ce";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x(0),yTempo(seq[0].features.tempo));for(let i=1;i<seq.length;i++){ctx.lineTo(x(i),yTempo(seq[i].features.tempo))}ctx.stroke();ctx.strokeStyle="#9b2c2c";ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(x(0),yEnergy(arc[0]||0));for(let i=1;i<arc.length;i++){ctx.lineTo(x(i),yEnergy(arc[i]))}ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#c8d1dc";ctx.font="12px Inter, sans-serif";ctx.fillText("Energy",pad+6,pad+12);ctx.fillStyle="#9aa6b2";ctx.fillText("Tempo",pad+66,pad+12)}

const SPOTIFY_CLIENT_ID=localStorage.getItem("sp_client_id")||"YOUR_SPOTIFY_CLIENT_ID";
function redirectUri(){
  const ov=localStorage.getItem("sp_redirect");
  if(ov && /^https?:\/\//i.test(ov)) return ov.endsWith("/")?ov:ov+"/";
  const o=window.location.origin||"";
  if(/^https?:/i.test(o)) return o.endsWith("/")?o:o+"/";
  return "http://localhost:3000/";
}
function b64url(buf){let s=btoa(String.fromCharCode.apply(null,new Uint8Array(buf)));return s.replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function sha256Buf(s){const enc=new TextEncoder().encode(s);const hash=await crypto.subtle.digest("SHA-256",enc);return new Uint8Array(hash)}
async function startLogin(){const verifier=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b=>("0"+b.toString(16)).slice(-2)).join("");const chBuf=await sha256Buf(verifier);const challenge=b64url(chBuf);localStorage.setItem("sp_verifier",verifier);const scope=["user-library-read","playlist-modify-public","playlist-modify-private","user-read-email","user-read-private"].join(" ");const url=new URL("https://accounts.spotify.com/authorize");url.searchParams.set("response_type","code");url.searchParams.set("client_id",SPOTIFY_CLIENT_ID);url.searchParams.set("scope",scope);url.searchParams.set("redirect_uri",redirectUri());url.searchParams.set("code_challenge_method","S256");url.searchParams.set("code_challenge",challenge);window.location.href=url.toString()}
async function exchangeCode(code){const verifier=localStorage.getItem("sp_verifier")||"";const body=new URLSearchParams();body.set("client_id",SPOTIFY_CLIENT_ID);body.set("grant_type","authorization_code");body.set("code",code);body.set("redirect_uri",redirectUri());body.set("code_verifier",verifier);const res=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!res.ok)return null;const tok=await res.json();const now=Math.floor(Date.now()/1000);localStorage.setItem("sp_access",tok.access_token);localStorage.setItem("sp_refresh",tok.refresh_token||"");localStorage.setItem("sp_exp",String(now+tok.expires_in-30));return tok.access_token}
function accessToken(){const exp=parseInt(localStorage.getItem("sp_exp")||"0",10);const now=Math.floor(Date.now()/1000);const t=localStorage.getItem("sp_access");if(!t||now>=exp)return null;return t}
async function handleAuthOnLoad(){const u=new URL(window.location.href);const code=u.searchParams.get("code");if(code){await exchangeCode(code);u.searchParams.delete("code");u.searchParams.delete("state");history.replaceState({},document.title,u.toString())}const t=accessToken();qs("#authStatus").textContent=t?"Spotify connected":"Not connected"}
async function apiFetch(url){const t=accessToken();if(!t)throw new Error("no_token");const res=await fetch(url,{headers:{Authorization:`Bearer ${t}`}});if(!res.ok)throw new Error("spotify_error");return res.json()}
function metaCluster(gen){const s=gen.join(" ").toLowerCase();if(/hip hop|rap|trap/.test(s))return "hip-hop";if(/house|techno|edm|electronic|dance/.test(s))return "electronic";if(/indie|alt/.test(s))return "indie";if(/rock|punk|metal/.test(s))return "rock";if(/r&b|rnb|soul/.test(s))return "r&b";if(/ambient|chill|downtempo|new age/.test(s))return "ambient";if(/pop|k-pop/.test(s))return "pop";return "pop"}
async function fetchSavedTracks(){let items=[];let url="https://api.spotify.com/v1/me/tracks?limit=50";for(let i=0;i<6;i++){const data=await apiFetch(url);items=items.concat(data.items||[]);const next=data.next;if(!next)break;url=next}const trackIds=items.map(it=>it.track?.id).filter(Boolean);const artistIds=Array.from(new Set(items.flatMap(it=>(it.track?.artists||[]).map(a=>a.id)).filter(Boolean)));const feats=await fetchAudioFeatures(trackIds);const artists=await fetchArtists(artistIds);const mapArtistGenres=id=>artists.get(id)||[];const tracks=[];items.forEach(it=>{const tr=it.track;if(!tr)return;const f=feats.get(tr.id);if(!f)return;const aIds=tr.artists.map(a=>a.id);const gRaw=Array.from(new Set(aIds.flatMap(mapArtistGenres)));const mc=metaCluster(gRaw);const genres=[mc].concat(gRaw.slice(0,2));tracks.push({id:tr.id,name:tr.name,artists:tr.artists.map(a=>a.name),genres,features:{energy:f.energy,valence:f.valence,danceability:f.danceability,acousticness:f.acousticness,instrumentalness:f.instrumentalness,tempo:Math.round(f.tempo),key:f.key,mode:f.mode}})});return tracks}
async function fetchAudioFeatures(ids){const out=new Map();for(let i=0;i<ids.length;i+=100){const chunk=ids.slice(i,i+100);const data=await apiFetch("https://api.spotify.com/v1/audio-features?ids="+encodeURIComponent(chunk.join(",")));(data.audio_features||[]).forEach(f=>{if(f&&f.id)out.set(f.id,f)})}return out}
async function fetchArtists(ids){const out=new Map();for(let i=0;i<ids.length;i+=50){const chunk=ids.slice(i,i+50);const data=await apiFetch("https://api.spotify.com/v1/artists?ids="+encodeURIComponent(chunk.join(",")));(data.artists||[]).forEach(a=>{if(a&&a.id)out.set(a.id,a.genres||[])})}return out}
async function saveToDB(tracks){try{const res=await fetch("/api/tracks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tracks})});return await res.json()}catch(e){return null}}
async function loadFromDB(){try{const res=await fetch("/api/tracks");const j=await res.json();return j.tracks||[]}catch(e){return []}}

async function me(){return apiFetch("https://api.spotify.com/v1/me")}
async function createPlaylist(name,desc,uid){const data=await fetch(`https://api.spotify.com/v1/users/${encodeURIComponent(uid)}/playlists`,{method:"POST",headers:{Authorization:`Bearer ${accessToken()}`,"Content-Type":"application/json"},body:JSON.stringify({name,description:desc,public:false})});if(!data.ok)throw new Error("create_failed");return data.json()}
async function addTracks(pid,uris){for(let i=0;i<uris.length;i+=100){const chunk=uris.slice(i,i+100);const r=await fetch(`https://api.spotify.com/v1/playlists/${encodeURIComponent(pid)}/tracks`,{method:"POST",headers:{Authorization:`Bearer ${accessToken()}`,"Content-Type":"application/json"},body:JSON.stringify({uris:chunk})});if(!r.ok)throw new Error("add_failed")}}
function seqUris(){const re=/^[A-Za-z0-9]{22}$/;return LAST_SEQ.filter(t=>re.test(t.id)).map(t=>"spotify:track:"+t.id)}
async function exportPlaylist(){try{const t=accessToken();if(!t){qs("#authStatus").textContent="Not connected to Spotify";return}if(!LAST_SEQ.length){qs("#authStatus").textContent="No playlist built";return}const uris=seqUris();if(!uris.length){qs("#authStatus").textContent="No Spotify tracks to export";return}qs("#authStatus").textContent="Creating playlist...";const prof=await me();const name=(qs("#playlistName")&&qs("#playlistName").value)||"AI DJ Session";const desc="Generated by AI Playlist DJ";const pl=await createPlaylist(name,desc,prof.id);await addTracks(pl.id,uris);qs("#authStatus").textContent=`Exported to ${pl.name}`;}catch(e){qs("#authStatus").textContent="Export failed"}}

function setupUI(){["energy","tempo","tempoBias","valence","danceability","acousticness","instrumentalness","genreWeight","length"].forEach(id=>{if(qs(`#${id}`))qs(`#${id}`).addEventListener("input",updateDisplays)});qs("#build").addEventListener("click",buildPlaylist);if(qs("#loadDemo"))qs("#loadDemo").addEventListener("click",()=>{DATA=genTracks(120);initGenres();updateDisplays()});if(qs("#useDemo"))qs("#useDemo").addEventListener("click",()=>{DATA=genTracks(120);initGenres();updateDisplays()});if(qs("#loginSpotify"))qs("#loginSpotify").addEventListener("click",startLogin);if(qs("#fetchLibrary"))qs("#fetchLibrary").addEventListener("click",async()=>{const t=await fetchSavedTracks();DATA=t;initGenres();updateDisplays()});if(qs("#saveDB"))qs("#saveDB").addEventListener("click",async()=>{const r=await saveToDB(DATA);qs("#authStatus").textContent=r&&r.ok?`Saved ${r.count}`:"Save failed"});if(qs("#loadDB"))qs("#loadDB").addEventListener("click",async()=>{const t=await loadFromDB();DATA=t;initGenres();updateDisplays()});updateDisplays()}
document.addEventListener("click",e=>{if(e.target&&e.target.id==="exportSpotify"){exportPlaylist()}})
async function bootstrap(){await handleAuthOnLoad();if(DATA.length===0)DATA=genTracks(120);initGenres();setupUI();updateDisplays()}
document.addEventListener("DOMContentLoaded",bootstrap);
